#include "AudioManager.hpp"

#include "Engine/Core/EngineCommon.hpp"

EXTERNED SoundID AUDIO_ANTICIPATION;
EXTERNED SoundID AUDIO_ATTRACT_MUSIC;
EXTERNED SoundID AUDIO_PLAY_MUSIC;

EXTERNED SoundID AUDIO_PAUSE_ACTIVATE;
EXTERNED SoundID AUDIO_PAUSE_DEACTIVATE;
 
EXTERNED SoundID AUDIO_PLAYER_SHOOT;
EXTERNED SoundID AUDIO_PLAYER_HIT;
EXTERNED SoundID AUDIO_PLAYER_DIED;

EXTERNED SoundID AUDIO_ENEMY_SHOOT;
EXTERNED SoundID AUDIO_ENEMY_HIT;
EXTERNED SoundID AUDIO_ENEMY_DIED;